### ISSUE TITLE
Schedule the final design reviews

### ISSUE THREAD

**Issue by moorepants** [moorepants/eme185#101]
Same as winter quarter method.

- [x] Look into getting nicer room than TB 207 since we are inviting all the sponsors.
- [x] Get instructor availability
- [x] Create signup form
- [x] Make assignment on Canvas
- [x] Reserve room(s)
- [x] Send out signup form
- [x] Resolve conflicts

**Comment by moorepants** [comment]
Kenny, what's the status on this?

**Comment by ixjlyons** [comment]
We've got a room (Bainer 2033) for 9-4 on all three days, so 21 slots total. Do you want to eliminate 12-1 so you're guaranteed a break?

@Gangchen01: could you fill in your availability so we can send out the form to students to sign up?

**Comment by moorepants** [comment]
A break for lunch is preferable for me.

**Comment by ixjlyons** [comment]
I've made an assignment on Canvas that's ready to go. @moorepants do you want to give them a full week to sign up? If so, you can just publish the assignment as is or let me know and I'll do it.

**Comment by moorepants** [comment]
Let's give them till Sunday midnight. So we can send invites to sponsors first of next week. Feel free to publish the assignment. I'd make an announcement too.

**Comment by ixjlyons** [comment]
Conflicts have been resolved. This is done finally.

**Comment by moorepants** [comment]
Great!
