### ISSUE TITLE
Add resources for Technical drawings

### ISSUE THREAD

**Issue by nav-go** [moorepants/eme185#110]
We need good resources for tech drawings and following standards. I've already added a section in the tech resources page.  If you have other resources, please add it there so we can consolidate in one place.

I can send out an announcement after the code is pushed to the live website.

**Comment by moorepants** [comment]
@nav-go Is this one done? If so, please close the issue, if not list what else we need to do.

**Comment by nav-go** [comment]
This was done last year. Closing the issue. We can keep adding more resources to the page as required.
