### ISSUE TITLE
Create and AIO template and example

### ISSUE THREAD

**Issue by moorepants** [moorepants/eme185#127]
We need a template for students to fill out. This should ensure that:

- Accomplishments, Issues, and Objectives, in that order
- Each A and O should have a person or persons name beside it, each name should have a time they spent or plan to spend.
- There should be a place for them to put in a relevant portion of their gantt chart and optionally a link to their full chart.
- Should be a space for optional attachments: images, tables, reports, etc
- Include a TO: and CC: fields with everyone that is supposed to get the email. Many students don't email the whole team or leave off some people. Should be all students in group, TA, and Jason, the client(s), and any other people that are intimately involved.
- I much prefer an email with this text and not an attachment to the email. The attachment is annoying and having to have various software to open it is annoying. Email allows rich text, so it's nice if it is just an email.
- Include the subject line in the template with the prefix so that they fill that out and copy it.

The example should show simple succinct As, Is, and Os.

**Comment by moorepants** [comment]
@swkresie I see you've started on a AIO template in GDocs. Note that these are requirements that may or may not be on this page: https://moorepants.github.io/eme185/pages/meetings.html.

I'll make comments on the template GDoc.

**Comment by swkresie** [comment]
I made my final edits to the google doc with the template for you to look over.  Once you approve, will I be putting it as a PDF file on Canvas and send out a Canvas announcement as well?

**Comment by swkresie** [comment]
I see you made some edits as well. I edited the Example AIO to reflect your accurately reflect your changes.

Shall I export a PDF and upload it to Canvas?

**Comment by moorepants** [comment]
I just moved the template to the public folder and shared it as such:

https://moorepants.github.io/eme185/pages/meetings.html

and sent an announcement.

Thanks for putting this together it looks great.
