### ISSUE TITLE
Create a meeting room in the design studio for Spring

### ISSUE THREAD

**Issue by moorepants** [moorepants/eme185#128]
Trying to figure out a better situation for meetings and presentations in the Spring. Thinking of dividers. More to come.

> Hi Jason,
> 
> I selected these options for room dividers.  Let’s chat about the sizes and arrangement that you need afterward.
> 
> https://www.versare.com/room-divider-360-accordion-portable-partition.html
> https://www.versare.com/straightwall-sliding-portable-partition.html
> https://www.schooloutfitters.com/catalog/product_info/pfam_id/PFAM1493/products_id/PRO4608
> 
> Best,
> Loan-anh Nguyen

**Comment by nav-go** [comment]
I was looking at dividers from the same company, a slightly taller model for better sound proofing.
https://www.versare.com/shop/portable-partitions/wall-mounted-room-dividers/operable-wall-folding-room-divider.html

The 19 feet length panel ($3,288) can create a 11x8' room along the corner with the TV. One table will be a tight fit. Having one 19 foot panel and one 11 foot ($2,532) will make it less claustrophobic.

**Comment by moorepants** [comment]
Decided against this. Just not enough room for the walls.
