### ISSUE TITLE
Skip the memo right after the first report

### ISSUE THREAD

**Issue by moorepants** [moorepants/eme185#13]
We need more time to grade and the students could use a break. (I'm feeling de ja vu typing this.)

**Comment by moorepants** [comment]
The syllabus needs to be fixed for this. Need to remove one memo in the winter quarter.

**Comment by ixjlyons** [comment]
So this time around we skipped the preliminary analysis memo (memo 5) that was scheduled to be due the week after report 1. There was an additional free week after that though. It seems like a worthwhile memo to have, so maybe just move it to the next week? Or would you rather have them focus on the preliminary design review and scrap the memo altogether?

**Comment by moorepants** [comment]
I've reduced things to four memos total, so this can be closed. It should lighten the load a bit.
