### ISSUE TITLE
Example Gantt Chart

### ISSUE THREAD

**Issue by moorepants** [moorepants/eme185#130]
After a couple of years I think that the Asana + InstaGantt might be the best free product to get them going on.

https://asana.com/apps/instagantt

Would be nice to have one that they can see. And show them how to do the screenshots.

**Comment by nav-go** [comment]
I sent Scott a good example of this from the Helios team last year. Could be used as an example.

**Comment by moorepants** [comment]
Do we have access to any team's full Gantt chart on Asana?

**Comment by moorepants** [comment]
Also this is a duplicate of #95

**Comment by nav-go** [comment]
Yes I have access to Helios's full gantt chart starting from Needs and specs memo. It's not super detailed though. Do you need a screenshot of it?

**Comment by moorepants** [comment]
I'll talk to you about it today in the meeting.

**Comment by moorepants** [comment]
I had a look at he Helios Gantt chart from last year. I isn't the best example of a Gantt chart. I basically only has several main tasks and they simply assigned each person to the task. For example, one task was something like "report 4" with four identical bars.

Another was "Fabricate Design". That should have sub-tasks, like "Machine mounting blocks" and "Machine propeller shaft" etc.

In your example tomorrow please have a bit more detail and let's now use the Helios one as a model. We'll need to find something better or make something.

**Comment by moorepants** [comment]
@swkresie Did we do this?

**Comment by swkresie** [comment]
I added a link to the shoe tying machine (2018 project) spring quarter gantt chart to the Reports page under the scheduling information section for report 1 and 2. I also added the link to the Meetings page where AIO content is described. I also added the link to the Gantt charts page.

**Comment by moorepants** [comment]
Thanks!
