### ISSUE TITLE
Create groups in canvas

### ISSUE THREAD

**Issue by moorepants** [moorepants/eme185#137]
Can you create all of the project groups in canvas and also create two master groups for the two sections which will be different than their registered section. See the spreadsheet in the "projects" folder. We need this to make all future assignments.

Use the Project ID as the group name.

Also, please add to the instructor guide if not there.

**Comment by moorepants** [comment]
@nav-go Sorry this wasn't clear.

Group Set #1: Group students by actual section they are attending with their team (not registered section)

Group Set #2: Group students by their projects.

#1 allows us to accept a single assignment per group and the grade gets mapped to all in the team.

#2 allows us to set different due dates for each section.

So, I created #2 so that the team charter assignment could work and I still need you to make #1. You can delete the A02/A03 group sets and replace with a single group set called "Sections".

**Comment by nav-go** [comment]
Got it. My understanding was that the projects document in the folder only has the registered section. I can go by the switched = true field in the project master list, where it is a bit unclear who replaced whom. Or I can use the emails you sent out to the groups and TAs as the final list showing which section they are attending. Could you forward the other two email chains to me?

**Comment by moorepants** [comment]
In the "Project Master Spreadsheet" the "Project Section" column indicates the teams' sections (not their registered section). This is the column you group by. There is also a "Studio Section" column and this represents which section the student registered in. The "Switched" column is True if "Project Section" == "Studio Section" and False otherwise. That should be sufficient, I'm not going to go forward all the emails.

**Comment by nav-go** [comment]
"Project section" is what I used before to create the group sets. Will use that again. Thanks for clearing this up.

**Comment by moorepants** [comment]
When you complete this, can you update the instructor guide so it is clearer? Thanks. I'll use the same column headings in the future.

**Comment by moorepants** [comment]
This is in the guide.
