### ISSUE TITLE
Making their own team placard could be a mini assignment for week 2

### ISSUE THREAD

**Issue by nav-go** [moorepants/eme185#139]
We could give them a basic format that specifies size , location and font of their team IDs. 

It could help be a early team building exercise and also sidesteps the preferred name issue.

**Comment by moorepants** [comment]
Sure, we could just give them a blank placard to fill out. I think last year, all we wrote on them was the team ID and they added their names and team name. I couldn't always read all the names but that worked. Fine with me if we print blank ones this year.

Don't won't to spend too much time on in in the future though, as it isn't clear to me what a specific learning objective would be for the exercise.

@swkresie @clayfanatic

**Comment by swkresie** [comment]
I can take their full names off of the current placards and have a spot to fill in their names and team name. I will keep the group ID on their as is.  I plan to go to Kinko's tomorrow afternoon to print them.

**Comment by moorepants** [comment]
We are just printing them and they can add their names. CLosing.
