### ISSUE TITLE
Quiz Review

### ISSUE THREAD

**Issue by clayfanatic** [moorepants/eme185#147]
Ch5 & 6 Quiz:
- remove non question question
- revise wording for all questions (long)

Ch18 Quiz:
- no specific comments for this quiz

Ch7 Quiz:
- Unused quiz, no feedback

Ch8 Quiz:
- Revise Pugh Concept Question wording, describe concept not specific name.

**Comment by clayfanatic** [comment]
CH10 Quiz:
https://github.com/moorepants/eme185/issues/149

**Comment by clayfanatic** [comment]
Updated Quiz 5 and 6; and Quiz 10

**Comment by moorepants** [comment]
We'll do Ch 7 this year, since we hopefully solve my miscommunication last year.

**Comment by clayfanatic** [comment]
Updated Quiz 8
