### ISSUE TITLE
Apply to exhibit at Maker Faire next year

### ISSUE THREAD

**Issue by moorepants** [moorepants/eme185#15]
A bunch of the projects will be appropriate for the Maker Faire and it would be fun to take a group down.

**Comment by ixjlyons** [comment]
Application deadlines for the Bay Area Maker Faire have passed this year. Note that the applications this year were February 12 and 19 for the Faire starting May 19.

http://makerfaire.com/bay-area/call-for-makers/

**Comment by moorepants** [comment]
It may not be realistic to ever do this. My other pipe dream would be to take the class on a field trip to Maker Faire.

**Comment by ixjlyons** [comment]
Added to instructor guide.
