### ISSUE TITLE
Canvas Assignment issue

### ISSUE THREAD

**Issue by nav-go** [moorepants/eme185#158]
Have you ever had an issue with editing a previous assignment and hitting "Save" or "Save and Publish" and nothing happens?

It doesn't seem to be a browser/cookies issue. I remember having this problem before but I don't remember what I did to fix it.

So far I've tried changing browsers, changing assignment parameters, incognito mode, and creating a new assignment. No idea why even creating a new assignment doesn't work. If this is an user permission issue then it shouldn't even let me edit.

**Comment by moorepants** [comment]
Thanks for fixing that!
