### ISSUE TITLE
Develop a report writing style guide

### ISSUE THREAD

**Issue by moorepants** [moorepants/eme185#166]
I like not having specific templates and such so that students have freedom to express things in ways that I don't know about. But it would be cool to create a style guide of sorts to give guidelines and good practices.

**Comment by clayfanatic** [comment]
Conference Template Style guide? e.g. ASME

**Comment by moorepants** [comment]
Cool, I'll have a look before the end of the week. I like the idea of the conference/journal style template. Make sure to get the bits that are currently on the website integrated. We could also take care of the #165 by including a few prints at the end of the template.

**Comment by moorepants** [comment]
You could use a B size print from here: http://www.moorepants.info/media/docs/cell-shearer-08-11-12.pdf Maybe find another different size, like C or D, and that would give them an example.

**Comment by moorepants** [comment]
This is done. Thanks.
