### ISSUE TITLE
Add a hazard assessment to the second report

### ISSUE THREAD

**Issue by moorepants** [moorepants/eme185#168]
- Hazard assessment: identify hazards and safety issues
- Hazard control: what are they going to do to minimize the hazards discover in 1.

There is a tool (a pyramid): https://en.wikipedia.org/wiki/Hierarchy_of_hazard_controls

**Comment by clayfanatic** [comment]
Would the hazard assessment would be aided by a risk assessment similar to this (likelihood vs consequence): https://safetyculture.com/topics/risk-assessment/

**Comment by clayfanatic** [comment]
Add hazards / risks prompt to Report 2 requirements.

**Comment by moorepants** [comment]
This is done. Very nice work!
