### ISSUE TITLE
Website says abstract on front page, template has abstract on second page

### ISSUE THREAD

**Issue by moorepants** [moorepants/eme185#182]
make consistent

**Comment by moorepants** [comment]
Let's leave the abstract on the front page.

@greg1877 Can you adjust the template?

**Comment by greg1877** [comment]
I can fix that.

I thought that I had accepted the invite when you sent it to me at the
beginning of the quarter.  Right now the link sends me to a 404.

**Comment by moorepants** [comment]
@greg1877 Is this fixed?

**Comment by moorepants** [comment]
@greg1877 ?

**Comment by greg1877** [comment]
It's done

**Comment by moorepants** [comment]
Great. Closing.
