### ISSUE TITLE
EME185B schedule Tip

### ISSUE THREAD

**Issue by mplefort** [moorepants/eme185#29]
Scheduling the second quarter 25 min meetings with instructor and TA's can be a large logistic issue. To ensure all parties are available during a meeting time, assign blocks of 50 min sections (25 min each group) in the course registrar with CRN numbers. Example: M 9-12 block with 3 blocks (9:00 - 9:50; 10:00-10:50; 11:00-11:50). 

Enforce TA's pick courses for next quarter by week 6 of quarter. Week 6 is first pass registration for undergraduates. 

Pick time blocks that match TA/Instructor/Major EME lecture times to avoid mass conflicts.

**Comment by moorepants** [comment]
@ixjlyons fyi

**Comment by ixjlyons** [comment]
Notes on this have been added to the instructor guide.
