### ISSUE TITLE
The Memorial Day Holiday causes there to only be 9 Mondays in the Spring Quarter

### ISSUE THREAD

**Issue by moorepants** [moorepants/eme185#30]
We need to schedule different times in the last week for Monday groups if they need the time.

**Comment by moorepants** [comment]
@ixjlyons We need to think about this too for Spring.

**Comment by ixjlyons** [comment]
It's too close to the end of the quarter to skip the meeting, so Monday meetings on the week of Memorial Day will be moved to Friday. This was noted on the signup sheet, so presumably teams are making sure the move will work for them.

**Comment by moorepants** [comment]
This is now in the instructor guide.
