### ISSUE TITLE
Create group charter assignment

### ISSUE THREAD

**Issue by moorepants** [moorepants/eme185#34]
- [x] Do some research and find a good template or example for a 1 page team charter (engineering focused preferably). Things I'd like to see: specifying main roles, people's teamwork styles, meeting times, meeting ground rules, etc. Show you recommendation to Jason before committing to it.
- [x] Create the Canvas assignment by Wednesday evening with a Friday (20th) 5pm due date.
- [x] This should include choosing company (team) names too. See https://github.com/moorepants/eme185/issues/17

**Comment by moorepants** [comment]
Here is an example: https://www.teamhelper.com/sample/TC_GuideSample.pdf

**Comment by ixjlyons** [comment]
I found a couple more examples:

* https://www.lce.com/Team-Charters-What-are-they-and-whats-their-purpose-1219.html
* http://www.npd-solutions.com/charterex.html

Here is a template from Oregon State's senior design course that seems to have the right sections:

* http://classes.engr.oregonstate.edu/mime/fall2011/ie497/Forms/team_charter.pdf

I'm thinking we can specify the sections their charters should contain as a sort of template and then link to an example or two to give them some idea of how they're written. Something like:

> A team charter is a document that specifies your team's purpose and the organizational principles you will use to fulfill that purpose. With your group members, select a company name, then write a 1-page charter stating: your company's purpose, its members and their roles, meeting times, and the decision-making process you will use to resolve conflicts and make progress.

**Comment by moorepants** [comment]
I like the simplicity of the Ice one but the Oregon State one is really good and thorough. I like page 2 of the OSU one. It is a form to fill out. I'd be fine if we give them a version of that. The only part I don't like is the project manager role. I don't want to force them to choose a leader (at all) or right now. It think it is better for that to evolve. I'd rather just have them layout preliminary roles that each person would like to play. It'd be nice if the OSU one is free from copyright so we could modify and republish publicly. If it isnt' then we can use modify and use internally to the class.

Maybe we can provide the reading parts on Canvas in the assignment or files and then have a front and back piece of paper for them to answer the questions. We will keep a hard copy of the charter.

Do you have time to put this together before class today? If so, maybe we should just do this in class.

**Comment by ixjlyons** [comment]
http://oregonstate.edu/about/copyright is 404 and the course site doesn't have anything either :/

No copyright/licensing notice essentially means "all rights reserved" correct? If not, I have a bit of time so I can adapt the first two pages of the OSU doc in time.

**Comment by moorepants** [comment]
Let's adapt it for our use and we will only share through Canvas. In the meantime, maybe send an email to the author and see if they care if you reuse and share.

How are we going to have the students fill it out? On paper? In class? Or pass out at end for homework?

**Comment by ixjlyons** [comment]
I think having them turn in a PDF makes sense so they can all refer back to it whenever. In that case, I guess they'd re-create the template and fill it in. A bit of wasted effort and they'd need to find a time to meet before Friday.

With a hard copy, they'd have to complete it during studio right? Unless we allow them to submit a scan on Canvas. I'm guessing it might take a half hour or so which would cut into the needs and specs activity quite a bit.

I think I'm leaning toward a Canvas assignment where they generate their own charter with a template to follow.

**Comment by moorepants** [comment]
> I think I'm leaning toward a Canvas assignment where they generate their own charter with a template to follow.

Sounds good.
