### ISSUE TITLE
Make a purchasing tips web page

### ISSUE THREAD

**Issue by moorepants** [moorepants/eme185#39]
Most spend too much on mcmaster and 80/20, etc.

Should include the EFL's vendor list.

**Comment by ixjlyons** [comment]
Got started on this [here](https://moorepants.github.io/eme185/pages/purchasing-tips). I could obviously use some help with the mechanical stuff.

Will add a link to it on the resources page (and purchasing guidelines?) once it's more complete.

**Comment by moorepants** [comment]
Blue Collar Supply is great for small metal pieces. There are also some recycle stores like the habitat for humanity one in Sac (I think). We need to have some basic plastics, composite, wood, and metal sources. Also add things like onlinemetals.com. The EFL's list is really the best thing here. There's is good. You can add Grainger too, as it is a UCDBuy option. There is also this "store" in the facilities compound on campus that has some basic things like a hardware store. They can get a PO and purchase from there. Quite convenient to walk to from Bainer.

The page looks good so far. I'll make some edits.

**Comment by moorepants** [comment]
Also, there are these new services that let you send them cad models and they send back 3d printed or machined parts.

The BAE shop can be hired to create parts that are too hard/time consuming/etc for the students to create.

**Comment by moorepants** [comment]
Add: http://www.sdp-si.com/

**Comment by moorepants** [comment]
This prof has a lot of nice resources: http://www.engr.sjsu.edu/bjfurman/courses/ME106/

**Comment by ixjlyons** [comment]
@moorepants any more major things to add/change?
