### ISSUE TITLE
Convert the g-drive rubrics to canvas

### ISSUE THREAD

**Issue by moorepants** [moorepants/eme185#48]
Canvas makes grading the reports collaboratively much easier. It is worth switching the rubrics over to that system.

- [x] Memo 3
- [x] Memo 4
- [ ] Memo 5
- [x] Memo 6
- [x] Report 1: Proposal
- [x] Report 2: Preliminary Design
- [x] Report 3: Midterm Update
- [x] Report 4: Final Report

**Comment by ixjlyons** [comment]
It seems the Canvas rubric is set up to have named criteria (e.g. organization) with optional long descriptions and short rating categories (poor, excellent, etc.), whereas the rubrics from last year have criteria names with descriptions for what puts a submission into each rating category.

Mapping to the Canvas format would essentially entail taking the description of the excellent category and using that as the criterion description. This makes the grading a little more ambiguous. On the other hand, putting long descriptions in for the category names will be a bit awkward (it's a one-line text box that doesn't wrap).

**Comment by moorepants** [comment]
I looked into this briefly last quarter with my EME 150A rubrics and ended up not converting them because I didn't have time to figure out how to map them all. I though that the Canvas rubrics did allow a table that looks like:

```
criteria 1 | poor | average | excellent
criteria 2 | poor |average | excellent
...
```

Some of these:

https://guides.instructure.com/m/4152/l/40072-how-do-i-add-a-rubric-to-an-assignment

seem to show it. We can discuss in person at the instructor meeting.

**Comment by ixjlyons** [comment]
Just to clarify what I mean, the existing rubrics have descriptions for what poor, average, and excellent  ratings mean for each of the criteria. The Canvas rubric format seems to be set up for something like:

```
criteria 1                        poor     average   excellent
    submission should have         1        3         5
    attributes a, b, and c.
criteria 2                        poor     average   excellent
    submission should have         1        3         5
    attributes d and e.
```

**Comment by moorepants** [comment]
Here is a Canvas rubric I created for a report in EME 150A:

![selection_101](https://cloud.githubusercontent.com/assets/276007/22003078/bf04429e-dc05-11e6-85a3-541d4d436237.jpg)

This seems similar to my Google Sheets rubrics for last year's EME 185. I think you can add text descriptions for each rating in each category.

**Comment by moorepants** [comment]
Kenny, I'll just keep doing these. I removed you from the task.
