### ISSUE TITLE
Update the purchasing info for this year

### ISSUE THREAD

**Issue by moorepants** [moorepants/eme185#49]
Felicia sent me an updated purchasing form.

**Comment by moorepants** [comment]
@ixjlyons Can you update this page: http://moorepants.github.io/eme185/pages/mae-purchsaing-guidelines.html with the information I just emailed you?

**Comment by ixjlyons** [comment]
Fixed with 2063746d798afd1d7094b162d9db6038302df1a3. I think that is the only change, though local purchasing instructions aren't in the guidelines. Was that something you added later or was it in the old version of the guidelines?

**Comment by moorepants** [comment]
Yes I must have added that as an extra item. We should leave that in.

**Comment by moorepants** [comment]
Haha, one a one line change. I thought it was more since she sent me that document. Thanks for the hard work :)
