### ISSUE TITLE
Create all assignments in Canvas

### ISSUE THREAD

**Issue by moorepants** [moorepants/eme185#51]
- [x] AIO (in class/attendance), note that this is per individual
- Reports
  - [x] Report 1
  - [x] Report 2
  - [x] Report 3
  - [x] Report 4
- Memos
  - [x] Memo 1
  - [x] Memo 2
  - [x] Memo 3
  - [x] Memo 4
  - [ ] Memo 5
  - [x] Memo 6
- Presentations
  - [x] Presentation 1
  - [x] Presentation 2
  - [x] Presentation 3
  - [x] Presentation 4

**Comment by ixjlyons** [comment]
We skipped memo 5 but I think this can be closed.
