### ISSUE TITLE
Setup the microcontroller lesson

### ISSUE THREAD

**Issue by moorepants** [moorepants/eme185#52]
Some things that need to be done:

- [x] Check the arduinos and components (at least a sample)
- [x] Order any replacement parts
- [x] Organize the kits
- [x] Transfer content on the slides for the "lab" portion to the website to have a complete "web version" of the materials.

@ixjlyons FYI, this is a task I'm going to want to you to take care of.

**Comment by ixjlyons** [comment]
Just to clarify the last task, they will still be shown slides during studio session, but there should be a more verbose version on the website like there is for part 1? Or is this to transition away from slides?

**Comment by ixjlyons** [comment]
All kits are complete and have batteries at 80%+ (checked with a battery tester).

**Comment by moorepants** [comment]
Great. Let's talk asap on whether we are going to improve the controller, as we'd need to order new parts.

**Comment by ixjlyons** [comment]
@moorepants: the tutorial is [live](https://moorepants.github.io/eme185/pages/part-2-implementing-a-pi-controller-with-an-arduino.html)
