### ISSUE TITLE
Create personalized sponsor thank you letters that go out at end of course.

### ISSUE THREAD

**Issue by moorepants** [moorepants/eme185#59]
Maybe these should come with some kind of certificate or something. We may be able to get MAE staff time to help with this. Jason needs to ask the chair.

**Comment by Gangchen01** [comment]
I have sent out the letters with the department envelops

**Comment by moorepants** [comment]
@Gangchen01 Does "closed" mean you've mailed them all out?

**Comment by Gangchen01** [comment]
Yes, I have mailed them all out, except the sponsors without address.

**Comment by moorepants** [comment]
Fabulous! What sponsors didn't have addresses? I thought I found them all.

**Comment by moorepants** [comment]
i just checked an all rows with TRUE for "send letter" have an address.
