### ISSUE TITLE
Create instructor guide

### ISSUE THREAD

**Issue by moorepants** [moorepants/eme185#60]
This will be a collaboratively created document that tries to capture everything that the instructors (me and the TAs) have to do to execute this class. I'd like the TAs to help me develop it while we move forward in the class.

The source is here: https://github.com/moorepants/eme185/blob/master/content/pages/instructor-guide.rst

And the rendered version: https://moorepants.github.io/eme185/pages/instructor-guide.html

**Comment by ixjlyons** [comment]
I've gone through and added the `note` label to a bunch of issues, most of which belong in the instructor guide. I'll make my way through them and catch up on the instructor guide in general this week.

**Comment by moorepants** [comment]
Great.

**Comment by moorepants** [comment]
I changed the label to "instructor guide".

**Comment by ixjlyons** [comment]
Currently, the instructor guide is written as a document for the TAs. Should it be reorganized a bit to be more generally addressed to all instructors?

**Comment by moorepants** [comment]
Yes, it should serve all instructors (both TAs and whoever the professor is that's leading it).

**Comment by moorepants** [comment]
The first pass of the guide is done. We now just have to improve and update each time the course is taught.
