### ISSUE TITLE
Encourage more authentic translation of user stories to needs

### ISSUE THREAD

**Issue by ixjlyons** [moorepants/eme185#63]
Students seem to go for the most straightforward translation of user story statements to needs, probably because they're thinking about the needs when they come up with the user stories.

One idea for encouraging less straightforward thinking when it comes to generating a list of needs is to ask them to write at least some of their user stories individually and then give them to another team member for translation.

**Comment by moorepants** [comment]
I'll say it today in class. Maybe we can improve it.

**Comment by moorepants** [comment]
Actually, can you edit the activity in google drive to include this? It will then be in place next year.

**Comment by ixjlyons** [comment]
Ok, done.
