### ISSUE TITLE
Create the team meeting schedule for the Spring

### ISSUE THREAD

**Issue by moorepants** [moorepants/eme185#65]

**Comment by ixjlyons** [comment]
How long are the Spring meetings for each team supposed to be?

**Comment by moorepants** [comment]
We have six 110 minute meetings at 17 groups. It looks like we will need to do 3 per section at 35 minutes each. Maybe each TA can sign up for 2 sections and we can see if the students schedules will work out with that. I'll comment more after dinner.

**Comment by moorepants** [comment]
I was thinking about this last night more. It'd be really nice if we can give them 45 minutes each in the spring. We did 20 minutes last year and it wasn't nearly enough time to talk about anything in depth. If we sectioned into two per section we could do 50-55 minute meetings. We'd just have to block of 3 more 110 blocks that are on the registrar. Call or chat me when you get in.

**Comment by moorepants** [comment]
I'm telling them in class this is due Friday Feb 10. Done. Thanks.
