### ISSUE TITLE
Create a guide to exporting Gantt charts

### ISSUE THREAD

**Issue by ixjlyons** [moorepants/eme185#70]
A step-by-step walk-through or at least some clear guidelines for how to generate a Gantt chart for attachment to AIOs/reports would be helpful for everyone. Most students seem to be using InstaGantt, so specific instructions for that tool would be good. Some general instructions would be nice for groups not using InstaGantt.

One potential issue with providing instructions for a single tool is it might be seen as a form of endorsement of that tool. Solutions would be to create instructions for other tools or to keep the guide general.

**Comment by moorepants** [comment]
I'm thinking that next year I'll just introduce asana and the instagantt plugin. I don't mind endorsing something, as long as they are free to use other tools they prefer. I'm seeing more and more cool uses of asana. It also has a trello style kankan board.

Just start with InstaGantt and we can the students in class which software they are using. If it's half/half we can add instructions for others.

**Comment by ixjlyons** [comment]
There doesn't seem to be an export option with InstaGantt that preserves the current date indicator. I'm not sure what to recommend. Taking a screenshot shows the current date but limits the date range shown and is fairly low-resolution.

**Comment by ixjlyons** [comment]
Page is up: https://moorepants.github.io/eme185/pages/gantt-charts.html

**Comment by ixjlyons** [comment]
If this looks good, should we make an announcement for future AIOs/reports?

**Comment by ixjlyons** [comment]
Not sure if this warrants re-opening the issue or creating a separate one, but I just found [Elegantt](https://elegantt.com/) which looks somewhat similar to InstaGantt but integrated with Trello rather than Asana.
