### ISSUE TITLE
Book meeting room for the Spring

### ISSUE THREAD

**Issue by moorepants** [moorepants/eme185#71]
It'd be nice if we could have a small room for <10 people with AV for displaying stuff from computers and a whiteboard. See if there are some possibility to reserve a room for all the sections. Second option is to use a single table in the design studio. This is generally fine but needs to be coordinated with Jacob Kitada. Last option is that I get more seats in my office somehow and we meet there.

**Comment by ixjlyons** [comment]
Got this done and added a few more notes to the instructor guide with 2409fb2

**Comment by moorepants** [comment]
FYI, I've decided that TB 207 is not good for these team meetings. Jacob has reserved a single table for us in the design studio for the duration of the spring quarter. We can keep TB 207 for the final design review.
