### ISSUE TITLE
Create the preliminary design review schedule

### ISSUE THREAD

**Issue by moorepants** [moorepants/eme185#72]
- This should be due the 22nd to give us some planning time.
- [ ] Reserve a room for this.
- [ ] Post this for students by the 15th (use ungraded assignment on canvas)

One hour blocks, e.g.:

- 9:00-9:05 : Setup
- 9:05-9:30: Presentation
- 9:30-9:50: Q&A
- 9:50-10:00: Grading

**Comment by ixjlyons** [comment]
I'll put this in the instructor guide later, but just making a quick note for now.

It's probably a good idea to get in touch with the office as early as possible to check for room availability. In terms of efficiently filtering time slots, I'd say the order is:

1. Instructor availability
2. Room availability
3. TA availability

So get Jason's availability, find out when rooms are available, make a spreadsheet and have TAs fill in availability, then use that to make a form for teams to fill in. Get the schedule to the office as soon as possible to reserve the rooms. Hopefully rooms getting booked during this process happens rarely enough to be able to fix issues as they arise.

**Comment by moorepants** [comment]
Yes, thanks. Sorry not having this prepped earlier. We can use multiple rooms too. It is unlikely we get a single room for every slot. Also, worst case scenario is we request use of the design studio (that's what we did last year for the winter quarter). In spring we were able to get the room that is now the maker space in bainer. So that's not available.

**Comment by ixjlyons** [comment]
This seems to be resolved. Some tips for getting the scheduling done have been added to the instructor guide.
