### ISSUE TITLE
Add description of team charter to website

### ISSUE THREAD

**Issue by ixjlyons** [moorepants/eme185#77]
The [memos page](https://moorepants.github.io/eme185/pages/memos.html#memo-2-team-charter-due-friday-january-20-2017) is missing a description for the team charter.

- [x] add description from Canvas assignment
- [x] ask for permission to re-use template
- [x] re-work template if needed
- [x] add link to template (either the adapted one or an original)

How should the template be served? .odt?

**Comment by ixjlyons** [comment]
Permission granted from John Parmigiani to adapt and use the team charter template here:

http://classes.engr.oregonstate.edu/mime/fall2011/ie497/

I used the template given to students this year as is and turned it into a [page](https://moorepants.github.io/eme185/pages/team-charter-template.html) (3350762).

**Comment by moorepants** [comment]
Nice!
