### ISSUE TITLE
Include the requirements to find standards and codes in the specification development

### ISSUE THREAD

**Issue by moorepants** [moorepants/eme185#80]
i need to get this into their thoughts more explicitly earlier on.

**Comment by moorepants** [comment]
Tony Passerini told me that he was able to get student access to online versions of certain ISO and other standards. He found that our library doesn't really have many of these physical texts because they are so expensive. Some that may be useful:

- OSHA
- ASHRAE
- ISO (not sure what numbers might be useful)
- ANSI

**Comment by ixjlyons** [comment]
I was wondering if it makes sense to add some instructional material on standards -- maybe dedicate a portion of a lecture or add a studio activity. Things like what standards organizations are, some of the main organizations, how to look for relevant standards. I don't think this kind of information is explicitly taught as part of the undergrad curriculum.

**Comment by moorepants** [comment]
Yes, I think we should have a lecture/activity associated with this in the winter.

**Comment by moorepants** [comment]
Closing because we have these in place now and #141 addresses the activity.
