### ISSUE TITLE
Create assignements on Canvas for the weekly AIO and meetings

### ISSUE THREAD

**Issue by moorepants** [moorepants/eme185#82]
@ixjlyons Can you create assignments similar to the existing AIO assignments for the Spring quarter? You can either make the 24 hour in advance due date for the M, T, W groups or we can make them all due Sunday nights at 11:59 pm. The Canvas interface allows the different due dates for sets of groups but it is a bit annoying to click to many times to set that up.

**Comment by moorepants** [comment]
I just told them that the are due 24 hrs in advance of the meeting but I think it would be ok to make the canvas due dates all the same, because the don't turn it in via Canvas. Just note this in the assignment so they don't get confused about it haven't two different due dates.

**Comment by ixjlyons** [comment]
Just making them due Sunday with a note about the 24-hour rule.
