### ISSUE TITLE
Make a formal agenda for meetings

### ISSUE THREAD

**Issue by moorepants** [moorepants/eme185#85]
So that there is something to talk about. Some groups just don't present anything.

@ixjlyons @Gangchen01 @nav-go 

I have a draft here: https://moorepants.github.io/eme185/pages/meetings.html

Please comment on it or edit it.

**Comment by ixjlyons** [comment]
I think the current page looks good. Maybe add a paragraph to explain what we discussed in our end-of-quarter meeting: basically that the studio session meetings in the Winter should have an agenda. I'll draft something up here.

**Comment by ixjlyons** [comment]
> In the studio sessions, your TA will circulate to meet with several teams for 30 each. During this meeting, you should spend at least the first 15 minutes talking about your AIO and discussing your upcoming plans in detail (using your Gantt chart). The remaining time can be spent discussing expectations for assignments, suggestions for improving memo/report quality, or other logistical issues.

**Comment by moorepants** [comment]
I think making the agenda more explicit with duration, title, and description of each thing to discuss. Mine could be improved with a title for each section like "Discuss accomplishments [10 minutes]" and "Review Gantt Chart and Objectives [10 minutes]". Make agendas for each quarter.

**Comment by ixjlyons** [comment]
One issue I hadn't thought of is whether or not there is an activity for the studio session. If we want an explicit agenda for the Winter, there should probably be two different versions to handle this. First pass:

if studio.activity is not None:

- 5 minutes: each team member takes turns describing their accomplishments
- 5 minutes: work through any issues that arose
- 5 minutes: make sure every team member has explicit objectives for the next week and update the Gantt chart to reflect this
- 5 minutes: discuss grading, logistics, upcoming assignments, etc.
- 10 minutes: collaborate on the activity

else:

- 15 minutes: each team member takes turns describing their accomplishments and going through any issues that arose
- 10 minutes: make sure every team member has explicit objectives for the next week and update the Gantt chart to reflect this
- 5 minutes: discuss grading, logistics, upcoming assignments, etc.


The reasoning behind the timing is that the activities are mostly scheduled early in the quarter when they don't have many issues/accomplishments to discuss.

Alternatively, we could just completely interrupt their progress on the activity and only focus on AIO stuff, but I thought I was able to do a good job helping with the activities and that ended up helping the projects overall in some cases.

**Comment by moorepants** [comment]
This sounds fine to me. Please add to the website.

**Comment by ixjlyons** [comment]
Added: https://moorepants.github.io/eme185/pages/meetings.html#meeting-agendas
