### ISSUE TITLE
Create a nicer poster template with UCD logo and better graphic design

### ISSUE THREAD

**Issue by moorepants** [moorepants/eme185#90]
There is an existing template in last year's drive folder. This should be a PowerPoint file as the main one but you can make other formats too if you want: libreoffice, g-docs, latex, etc. But PP is sufficient.

**Comment by ixjlyons** [comment]
There's now a sort of template/example in Drive. I created it with LibreOffice Impress (saving it as an odp file) and it seemed to convert to Google Sheets flawlessly. I did have to explicitly save it as a ppt file from LibreOffice to get it to open properly in PowerPoint, however.

It took...a while since I'm used to poster-making in Inkscape. Comments would be helpful. I didn't want to be too preachy but a couple things that bug me are tiny text and low-res graphics.

**Comment by moorepants** [comment]
It looks great! Make the "Faculty Advisor" be "Advisors" or "Sponsors" and indicate that more than one person can be listed.

Note these things I have: https://moorepants.github.io/eme185/pages/presentations.html#engineering-design-showcase-poster-presentation. In particular the scientific poster tips is a really nice pdf that give most tips. So we don't have to cover that too.

We should link from our website to three versions: PPT, ODS, and Google Pres (if it converts to SVG, you can do that too).

Did you use the exact UCD blue and yellow from the marketing site suggestions?

The ENG 4 posters are pretty nicely laid out with specific sections. You could ask Duff Harrold (TA for the class) what they provide to see if that gives any good ideas to compare to.

**Comment by moorepants** [comment]
One nit pick, can the white on the UCD logo (book, etc) be changed to the blue and if so, would that look better?

**Comment by ixjlyons** [comment]
> Did you use the exact UCD blue and yellow from the marketing site suggestions?

Yes, the header is the web color on the marketing site. The seal is the informal one, which they say not to use on presentations, websites etc. I'm assuming this usage is ok.

> One nit pick, can the white on the UCD logo (book, etc) be changed to the blue and if so, would that look better?

Yeah, this is a bit of an issue. It looks best with the dark blue background for the pages and ribbon to be filled with the matching color, but that looks kind of bad if they just want to change the header background color. The white fills are a bit more versatile in that it looks alright with any dark background. Can't just get rid of the fills either :/

I guess it kind of depends on what they'll do with the template. I'm assuming a good number of teams are just going to completely copy the appearance and fill in their own content. Others might get more creative and change things up, in which case they should be aware that they can download the high-res logos and use the one that works best.

Anyway, I've updated the version on drive. I think as a template, it serves its purpose, but it ended up as kind of a weird mashup of an example and a template. Do you think it's clear enough, for example, that they should change the section heading "Secondary Point" to something like "LHC Experiments"?

**Comment by ixjlyons** [comment]
By the way, I found a pretty nice actual example:

https://doi.org/10.5281/zenodo.168068

Doing a search for neat topics and filtering to posters on Zenodo should pull up more examples pretty easily.

**Comment by moorepants** [comment]
Can we get this posted to the website? Feel free to start a section for examples of good posters.

**Comment by ixjlyons** [comment]
GitHub Pages seems slow to update today, but this should soon be a live link to the new template section added:

https://moorepants.github.io/eme185/pages/presentations.html#template

I think it worked out well that downloading from Google Slides to odp or pptx files works well for PowerPoint and LibreOffice. I tested with LibreOffice 5.3.2 and PowerPoint 2013.

**Comment by ixjlyons** [comment]
If all looks good we can announce to the class and close.

**Comment by moorepants** [comment]
Looks good to me. Feel free to announce that you've added the materials to the website.
