### ISSUE TITLE
Invite folks to the design showcase and/or design reviews

### ISSUE THREAD

**Issue by moorepants** [moorepants/eme185#91]
Draft up an email or emails that invites all of these folks to the showcase. This should be very nice and professional. Maybe we can include some highlights from last year and a few teasers for this year. Draft the mail and ask Jason to review it. He can send the mail from his account once done.

People to invite to showcase:

- [x] MAE Faculty
- [x] MAE Staff
- [x] EFL Staff
- [x] EME 185 Panelists
- [x] EME 185 Sponsors and Advisors
- [ ] EME Advisory board (we should ask the chair about this)
- [x] Meijo Group that is visiting (separate email that Kenny handles)

People to invite to design reviews:

- [ ] MAE Faculty
- [ ] EFL Staff
- [x] EME 185 Sponsors and Advisors
- [ ] Meijo Group that is visiting

**Comment by moorepants** [comment]
@Gangchen01 I've updated this task and put a week 6 deadline on it.

**Comment by Gangchen01** [comment]
@ixjlyons   Kenny, where will the final design review happen, do we need to book a conference room now?

**Comment by ixjlyons** [comment]
They're all going to be in Bainer 2033.

**Comment by moorepants** [comment]
@Gangchen01 Did you send only to the sponsors? If so, I will forward it to the faculty and EFL staff.

**Comment by Gangchen01** [comment]
@moorepants  Yes, I just sent email to sponsors only!
Please forward it to the faculty and EFL staff. Thanks.

**Comment by moorepants** [comment]
Closing this. Not going to invite the remaining folks as the showcase is plenty.
