### ISSUE TITLE
Tidy up the space in Bainer 1071A

### ISSUE THREAD

**Issue by moorepants** [moorepants/eme185#92]
- [ ] Get boat team to box up things and move to Bainer 1231.
- [ ] Clean up the space in 1071A (no trash, no eme 185, no boat stuff)

**Comment by ixjlyons** [comment]
Does the back of the room need to be cleaned out once the solar boat team is done?

**Comment by moorepants** [comment]
The space should be completely clear of EME 185 and boat stuff by week 7. All trash or mess should be cleaned up. We will need to get the boat team to box up their things after competition. We'll put everything but the boat in Bainer 1231 and I need to ask Mike if we can store the actual disassembled boat in there too. For now the boat will stay at the Campus Heating and Cooling.

I've changed the list above to reflect this.
