### ISSUE TITLE
Organize the June Meijo visit

### ISSUE THREAD

**Issue by moorepants** [moorepants/eme185#93]
- [ ] See about some other lab tours for the Friday that they are here.
- [ ] Make schedule on g drive (need this earlier than last time so they have more time to review)
- [ ] The lunch this time could be Friday june 9th and maybe we just try to have the bottlecap and paper airplane teams. We can do their "cultural design" presentations there.
- [x] Ask Alin Wakefield for tables beside our teams at the showcase so the Japanese teams can display too.
- [ ] Prep the cultural exchange: print grading rubric, etc

**Comment by ixjlyons** [comment]
Getting started on this now. Things that would be good to know as soon as possible:

- how many people are coming?
- arrival and departure dates/times

**Comment by moorepants** [comment]
I have some notes with this info somewhere on a piece of paper but it will probably be faster to ask Petros via email for the details. The dates are approximately June 7th through 13th.

**Comment by moorepants** [comment]
Also, I added a milestone to this.

**Comment by ixjlyons** [comment]
Just got word from him that they're arriving on the 4th and want to leave Davis either late on the 8th or after lunch on the 9th. This means they'll miss the design reviews. I suppose they could sit in on some of the regular meetings that week.
