### ISSUE TITLE
Create example materials

### ISSUE THREAD

**Issue by moorepants** [moorepants/eme185#95]
It'd be very helpful if we had examples (maybe even good, average, and poor) of things like reports, memos, posters, aio's, gant charts, etc. The list below will track all of the things that need to be created:

- [ ] Gant Chart
- [x] Technical report
- [x] AIO
- [x] Bill of Materials
- [x] Mechanical drawings
- [x] Electrical diagram
- [ ] If we provide generic sets of milestones for the 3 to 5 common project types up front this will give them and idea of how to layout their schedule. See #36
- [x] Posters
- [ ] How to present software design and code
- [ ] UX design docs

**Comment by moorepants** [comment]
@ixjlyons @nav-go @Gangchen01 Can you all please review this updated section on the website:

**Comment by moorepants** [comment]
@ixjlyons @Gangchen01 @nav-go Can you all please review this updated section on the website:

https://moorepants.github.io/eme185/pages/reports.html#technical-documentation-explanation-and-examples

Please edit and add as you see fit. If you have some other good examples that we can add for any of the above items (or any other relevant thing) please do so. Give me feedback here or at the meeting.

**Comment by ixjlyons** [comment]
I don't know if you'd consider IKEA assembly instructions good examples of user assembly manuals, but they provide PDFs for seemingly all of their products: http://www.ikea.com/ms/en_US/customer_service/assembly_instructions.html

The restriction of using basically no text at all generates pretty creative and clear instructions sometimes.

**Comment by moorepants** [comment]
Those are great examples. Add a link with a note similar to your last line above.

**Comment by moorepants** [comment]
Closing in favor of #130 and we can open new issues for other items.
