### ISSUE TITLE
Deal with missing whiteboard

### ISSUE THREAD

**Issue by moorepants** [moorepants/eme185#98]
- [x] Try to find our missing whiteboard. There should be six of them in the room.
- [x] Permanently label the whiteboards with "Belongs in Bainer 2071" or "Stolen from Bainer 2071".

**Comment by moorepants** [comment]
I currently have asked Jacob to work on this.

**Comment by moorepants** [comment]
We should ask the Bainer janitorial staff if they have seen it.

**Comment by moorepants** [comment]
Update: The janitors found the whiteboard in Bainer 0302 and I'm in the process of getting it back.

**Comment by moorepants** [comment]
@ixjlyons As mentioned, can you engrave the white boards to say:

"Property of MAE, Belongs in Bainer 2071" (or if too long shorten)

**Comment by ixjlyons** [comment]
So the laser engraver can engrave aluminum, but it has to be anodized. Apparently there is a coating you can apply, engrave over, then remove as well. Either way the whiteboards are too large to fit into the machine in the EFL. They don't appear to be easily disassembled/assembled, but I could be wrong about that.

One option involving engraving would be to make some aluminum "tags" that can be screwed into the frame or even in the corner of the whiteboard face. That would actually be pretty effective -- you could just repeat the pattern onto a long strip of 1/16" aluminum and chop it up into 6 or 12 tags.

A few other simple options I can think of:

- Print out labels on a label maker. Quick, simple, and cheap. Not permanent.
- Use lettering punches. Simple, cheap. Not quick, not very pretty, maybe too small.
- Write with a marker. Quick, simple. Not pretty, semi-permanent.

**Comment by moorepants** [comment]
How about a paint marker?

**Comment by ixjlyons** [comment]
That should work, though my penmanship isn't the greatest. Actually, I could get a polyimide stencil made from [OSH Stencils](https://www.oshstencils.com/) for $(a few).

**Comment by ixjlyons** [comment]
Welp, after all that I just wrote on them by hand with a Rust-Oleum paint pen. They probably would've turned out nicer if I just written more fluidly instead of trying too hard to be precise, but I kinda got the hang of it toward the end:

![img_20170615_121323](https://user-images.githubusercontent.com/943602/27198118-c86d14e2-51c5-11e7-9e68-542a86525660.jpg)

Maybe in the future it can be covered up with something cooler.

**Comment by moorepants** [comment]
Thanks. Looks great. Hopefully we can keep them in the room from now on.
