### ISSUE TITLE
Get electricity usage monitors

### ISSUE THREAD

**Issue by ixjlyons** [moorepants/eme185#99]
A Kill A Watt is about $20 -- should we just get two?

@moorepants are the Meijo teams planning to be able to use a 120V NEMA outlet?

**Comment by moorepants** [comment]
Can you find out from petros the electricity needs for them? I think Japan is on the same voltage, just needs an adapter for plug shape.

Two is fine.

The should be charged to my EME 185 account, which I don't know the number. Ask Jen Young.

**Comment by ixjlyons** [comment]
Haven't heard back yet, so I'll send a follow-up. In the meantime, I looked into it a bit and it seems the sockets in the US and Japan are essentially physically the same. Japan outlets provide 100V with some at 50Hz and some at 60Hz. A proper 120V to 100V converter is around $40, but I don't think it's necessary because most AC adapters accept some range of inputs like 100-240V at either 50/60Hz.

**Comment by moorepants** [comment]
Haven't heard back from Petros, Jen Young, or both? FYI, Petros is coming by here on Friday. I'll schedule so we can both meet with him.

**Comment by ixjlyons** [comment]
Was referring to Petros -- sorry, I hadn't re-read the previous message.

**Comment by ixjlyons** [comment]
For the record, we're moving forward assuming the Meijo teams will be able to use US power without issue.

Order for the electricity usage monitor has been placed.

**Comment by ixjlyons** [comment]
Picked these up yesterday. I can hang on to them and bring them to the competition.

**Comment by moorepants** [comment]
Once one of the machine is running here, try them out and see if it can actually measure what we want.

**Comment by ixjlyons** [comment]
I had the bottlecap team run a bottle through with the meter today. A couple things:

I think what we want to know is the energy consumption per bottle cap removal (in Watt-seconds). The kill-a-watt monitor displays instantaneous power in Watts (at about 2 Hz), and it provides an integrated power in kilowatt-hours. The issue is that this kWh monitor is meant for long-term monitoring and its resolution is 10 Watt-hours. If we wanted to accurately measure the energy consumption per bottle cap removal, you'd have to run the machine continuously until the kWh meter increments and count the number of bottles processed. At 60 Watts (approximate power consumption of UCD bottlecap team's design), this will take 10 minutes to increment the kWh meter. I'm guessing 60 Watts would be on the high end compared to the Meijo bottlecap design and both paperplane designs.

What we can do is take video of the Watt meter while the machine processes N bottles, watch it back hat half speed to take down the output each time it updates, integrate, and divide by N. The monitor might just be a zero order hold, but it's possibly sampling more rapidly and averaging to produce a somewhat smooth meter output (I played around with it a bit and I think it is the latter). Either way, I think it's reasonable to do the test this way despite the chance of peak power consumption occurring between samples. I was surprised how steady the power consumption of the UCD bottlecap team's design was, so it shouldn't be an issue unless the Meijo team's cap removal happens extremely quickly.

All this should hold for the paperplane projects as well.

In the future, it may be worthwhile to look around for a power/energy monitor that can be hooked up to a DAQ. I'm guessing that would be in a totally different price range compared to a consumer product like the kill-a-watt though.

**Comment by ixjlyons** [comment]
For the record, Professor Linke let us borrow a Watts up? PRO, which looks like it has 0.001 Wh increments, though it only updated in 0.1 Wh increments (which was fine). The Watts up? standard model is about $100 [[link]](https://www.wattsupmeters.com/secure/products.php?pn=0&wai=618&more=5).
